#!/bin/bash
#
# Make the complete QuickUI site from the component projects, quickui and
# quickui-catalog. For now, this script expects those companion projects to be
# cloned to peer folders to this one.
#

# Get location of parent QuickUI folder relative to location of this script.
scriptPath=$(cd ${0%/*} && echo $PWD/${0##*/})
scriptFolder=`dirname "$scriptPath"`
sitePath="$scriptFolder/.."

releasePath="$sitePath/release"
if [ ! -d "$releasePath" ]; then
	echo "Creating release folder"
    mkdir "$releasePath"
fi

echo Building QuickUI runtime
quickuiSource="$sitePath/../quickui"
grunt --color=false --config $quickuiSource/grunt.js

# TODO: run unit tests

# Extract version line from quickui.js, which looks like
# 	quickui: "0.9.1"
quickuiRuntimeBaseName="$quickuiSource/quickui"
versionLine=`grep "quickui:" $quickuiRuntimeBaseName.js`
# Extract the version number from that line.
version=`echo $versionLine | sed -e "s/.*quickui: \"\(.*\)\"/\1/"`

# Unfortunately, OS/X version of cp doesn't support --update
os=`uname`
if [[ "$os" == "Darwin" ]]; then
   updateParam=""
else
   updateParam="--update"
fi

echo Copying QuickUI runtime files
# cp options are: force, preserve (times), update (if available)
cp -fp $updateParam $quickuiRuntimeBaseName.* $releasePath

echo Copying versioned runtime files for version $version
cp -fp $updateParam $quickuiRuntimeBaseName.js $releasePath/quickui-$version.js
cp -fp $updateParam $quickuiRuntimeBaseName.css $releasePath/quickui-$version.css

echo Building catalog
catalogSource="$sitePath/../quickui-catalog"
grunt --color=false --config $catalogSource/grunt.js all

#grunt --config $catalogPath/grunt.js
# TODO: run unit tests

echo Copying catalog runtime files
catalogRuntimeBaseName="$catalogSource/quickui.catalog"
cp -fp $updateParam $catalogRuntimeBaseName.* $releasePath

# Extract version line from quickui.catalog.js, same as for quickui.js (above).
catalogVersionLine=`grep "catalog:" $catalogRuntimeBaseName.js`
catalogVersion=`echo $catalogVersionLine | sed -e "s/.*catalog: \"\(.*\)\"/\1/"`

echo Copying versioned catalog runtime for version $catalogVersion
cp -fp $updateParam $catalogRuntimeBaseName.js $releasePath/quickui.catalog-$catalogVersion.js
cp -fp $updateParam $catalogRuntimeBaseName.css $releasePath/quickui.catalog-$catalogVersion.css

echo Copying catalog resources
catalogResourcesSource="$catalogSource/resources"
cp -fpr $updateParam $catalogResourcesSource $releasePath

catalogDest="$sitePath/catalog"
if [ ! -d "$catalogDest" ]; then
	echo Creating catalog documentation folder
	mkdir "$catalogDest"
fi
echo Copying catalog documentation
cp -fpr $updateParam $catalogSource/docs/* $catalogDest

echo Compiling site markup
qb $sitePath

echo Building site
grunt --color=false ---config $sitePath/grunt.js

echo Building demos
demosSource="$sitePath/../quickui-demos"
qb $demosSource

echo Copying demos
demosPath="$sitePath/demos"
if [ ! -d "$demosPath" ]; then
	echo Creating demos folder
	mkdir "$demosPath"
fi
cp -fpr $updateParam $demosSource/* $demosPath