#!/bin/bash
# Make the complete QuickUI site from the component projects, quickui and
# quickui-catalog.

# Get location of parent QuickUI folder relative to location of this script.
scriptPath=$(cd ${0%/*} && echo $PWD/${0##*/})
scriptFolder=`dirname "$scriptPath"`
sitePath="$scriptFolder/.."

quickuiPath="$sitePath/../quickui"

grunt --config $quickuiPath/grunt.js
# TODO: run unit tests
rsync -rt $quickuiPath/src/quickui.* release/
# TODO: extract version and create release/quickui.<version>.js and .css

catalogPath="$sitePath/../quickui-catalog"
grunt --config $catalogPath/grunt.js
# TODO: run unit tests
qb $catalogPath
rsync -rt $catalogPath/quickui.catalog/quickui.catalog.* release/
rsync -rtv --exclude "build" --exclude ".DS_Store" $catalogPath/docs/ catalog/
