#!/bin/bash
# Make the complete QuickUI site from the component projects, quickui and
# quickui-catalog.

# Get location of parent QuickUI folder relative to location of this script.
scriptPath=$(cd ${0%/*} && echo $PWD/${0##*/})
scriptFolder=`dirname "$scriptPath"`
sitePath="$scriptFolder/.."

releasePath="$sitePath/release"
if [ ! -d "$releasePath" ]; then
	echo "Creating release folder"
    mkdir "$releasePath"
fi

echo "Building QuickUI runtime"
quickuiSource="$sitePath/../quickui"
grunt --color=false --config $quickuiSource/grunt.js

# TODO: run unit tests
echo "Copying QuickUI runtime files"
cp --force --update $quickuiSource/src/quickui.* release
# TODO: extract version and create release/quickui.<version>.js and .css

echo "Building control documentation"
catalogSource="$sitePath/../quickui-catalog"
$catalogSource/mkdocs

#grunt --config $catalogPath/grunt.js
# TODO: run unit tests

echo "Building catalog runtime"
catalogRuntime="$catalogSource/quickui.catalog"
qb $catalogRuntime

echo "Copying catalog runtime files"
cp --force --update $catalogRuntime/quickui.catalog.* release

echo "Building catalog documentation"
qb $catalogDest

catalogDest="$sitePath/catalog"
if [ ! -d "$catalogDest" ]; then
	echo "Creating catalog documentation folder"
	mkdir "$catalogDest"
fi
echo "Copying catalog documentation"
cp --recursive --update $catalogSource/docs/* $catalogDest
